version: '3'
services:
  web:
    build:
      ./UI/docker-practice-ui/
    ports:
      - "4000:3000"
    depends_on:
      - server
  server:
    build: ./Server/docker-practice-server/
    ports:
      - "3000:3000"
    depends_on:
      - migrator
  db:
    image:
      cassandra:latest
    ports:
      - "9043:9042"
  migrator:
    build:
      ./Migrator/Migrator/
    depends_on:
      - db
    restart:
      on-failure