version: '3'
services:
  web:
    build:
      context: ../../UI/docker-practice-ui
      dockerfile: ./Docker/Debug/Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ../../UI/docker-practice-ui/:/usr/src/app
    command: sh -c 'while ! nc -z server 3030; do echo "... connecting to server" && sleep 1; done && echo "Server is up and running" && npm start'
  server:
    build:
      context: ../../Server/docker-practice-server
      dockerfile: ./Docker/Debug/Dockerfile
    ports:
      - "3005:3030"
    volumes:
      - ../../Server/docker-practice-server/:/usr/src/app
    restart:
      on-failure
  db:
    image: cassandra:3.7
    ports:
      - "9042:9042"
  migrator:
    build:
      context: ../../Migrator/Migrator
      dockerfile: ./Docker/Debug/Dockerfile
    command: sh -c 'while ! nc -z db 9042; do echo "... connecting to cassandra" && sleep 1; done && echo "Cassandra is up and running" && dotnet Migrator.dll'