version: '3'
services:
  server:
    build:
      context: ../../Server/docker-practice-server
      dockerfile: ./Docker/Release/Dockerfile
    ports:
      - "3005:3030"
    restart:
      on-failure
  web:
    build:
      context: ../../UI/docker-practice-ui
      dockerfile: ./Docker/Release/Dockerfile
    ports:
      - "4000:3000"
    command: sh -c 'while ! nc -z server 3030; do echo "... connecting to server" && sleep 1; done && echo "Server is up and running" && npm start'
  db:
    image: cassandra:3.7
  migrator:
    build:
      context: ../../Migrator/Migrator
      dockerfile: ./Docker/Release/Dockerfile
    command: sh -c 'while ! nc -z db 9042; do echo "... connecting to cassandra" && sleep 1; done && echo "Cassandra is up and running" && dotnet Migrator.dll'